### ISSUE TITLE
Attribute Error When Running Examples

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/SparseConvNet#27]
Hi Benjamin, thank you for your contribution of designing this wonderful SparseConvNet, and I have encountered a problem while running the examples provided by you, hopefully you can help me with it.

When I ran the scripts `hello-world.py` under `SparseConvNet/examples` or `ResNet.py` under `SparseConvNet/examples/Assamese_handwriting/`, there was a same attribute error:

```
File "/root/SparseConvNet/PyTorch/sparseconvnet/submanifoldConvolution.py", line 94, in forward
    output.features=ValidConvolutionFunction.apply(
```

The full traceback is: (take the ResNet.py case as an example)

```
File "ResNet.py", line 45, in <module>
    'check_point': True,})
  File "/root/SparseConvNet/PyTorch/sparseconvnet/classificationTrainValidate.py", line 90, in ClassificationTrainValidate
    output = model(batch['input'])
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "ResNet.py", line 29, in forward
    x = self.sparseModel(x)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/SparseConvNet/PyTorch/sparseconvnet/submanifoldConvolution.py", line 94, in forward
    output.features=ValidConvolutionFunction.apply(
AttributeError: type object 'ValidConvolutionFunction' has no attribute 'apply'
```

After looking into the file `submanifoldConvolution.py`, I found that there is actually no `apply` that belongs to `ValidConvolutionFunction`, but there is a `forward` function whose API seems can fit here. However, the parameter number failed to match (the function requires 8 but only 7 are provided). I added `self` as the 1st parameter, but a new error raised.

I wonder how can I fix this problem? Thank you very much.

**Comment by btgraham** [comment]
Thanks for the report. What version of torch are you using please? i.e.
`import torch`
`print(torch.__version__)`

**Comment by CaesarPan** [comment]
Hi Benjamin,

Thank you for your reply. Its version is `0.1.12_1`

**Comment by btgraham** [comment]
Please try upgrading to a recent version of PyTorch.  The autograd API changed from 0.1 to 0.2; it is now on version 0.3!

**Comment by CaesarPan** [comment]
Hi Benjamin,

The error disappeared after I upgraded PyTorch to 0.3, yet another runtime error raised, and I have opened another issue. Thank you for your help.
