### ISSUE TITLE
 fatal error: torch/extension.h: No such file or directory  #include <torch/extension.h>

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/SparseConvNet#58]
gcc-5 and pytorch 0.4.1 got this error. more messages:

```
➜  SparseConvNet git:(master) ✗ sudo python3 setup.py install         
running install
running bdist_egg
running egg_info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -.o -std=c++11 -fopenmp -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
sparseconvnet/SCN/sparseconvnet_cuda.cpp:14:10: fatal error: torch/extension.h: No such file or directory
 #include <torch/extension.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by btgraham** [comment]
SparseConvNet has been updated to work with PyTorch 1.0. With conda, please try:

```
conda install pytorch-nightly -c pytorch # See https://pytorch.org/get-started/locally/
conda install google-sparsehash -c bioconda   # OR apt-get install libsparsehash-dev
conda install -c anaconda pillow
git clone git@github.com:facebookresearch/SparseConvNet.git
cd SparseConvNet/
bash build.sh
```
